import {
  ArrowLeft,
  Home,
  Search,
  PlusCircle,
  List,
  User,
  ArrowDownUp,
  Star,
  Shapes,
  History,
  ChevronDown,
  Bell,
  ShoppingBag,
  TabletSmartphone,
  Pill,
  Brush,
  Joystick,
  MoreHorizontal,
  Plus,
  X
} from "lucide-react-native";
import { iconWithClassName } from "./iconWithClassName";
iconWithClassName(ArrowLeft);
iconWithClassName(Home);
iconWithClassName(Search);
iconWithClassName(PlusCircle);
iconWithClassName(List);
iconWithClassName(User);
iconWithClassName(ArrowDownUp);
iconWithClassName(Star);
iconWithClassName(Shapes);
iconWithClassName(History);
iconWithClassName(ChevronDown);
iconWithClassName(Bell);
iconWithClassName(ShoppingBag);
iconWithClassName(TabletSmartphone);
iconWithClassName(Pill);
iconWithClassName(Brush);
iconWithClassName(Joystick);
iconWithClassName(MoreHorizontal);
iconWithClassName(Plus);
iconWithClassName(X);
export {
  ArrowLeft,
  Home,
  Search,
  PlusCircle,
  List,
  User,
  ArrowDownUp,
  Star,
  Shapes,
  History,
  ChevronDown,
  Bell,
  ShoppingBag,
  TabletSmartphone,
  Pill,
  Brush,
  MoreHorizontal,
  Plus,
  X
};
