name: Add Feature
description: This is the template for adding features to the web application. (Feature Backlogs)
title: "[FEAT] <Feature Title/Name Here> "
labels: ["feat"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Fill up the required fields below.
  - type: textarea
    id: user-stories
    attributes:
      label: User Story(ies)
      description: Provide user stories for this feature. You may input more than one, but in bullet form please!
      placeholder: “As a [persona], I [want to], [so that].”
      value: "- As a [persona], I [want to], [so that]."
    validations:
      required: true
  - type: dropdown
    id: estimation
    attributes:
      label: Estimation
      description: Provide the t-shirt size estimation of this feature.
      options:
        - XS - Done under 6 hours
        - S - Done under a day
        - M - Done under 2 days
        - L - Done under 3 days
        - XL - Done under a week
        - XXL - Done under 10 days
    validations:
      required: true
  - type: dropdown
    id: priority-level
    attributes:
      label: Priority Level
      description: Provide the priority level for this feature
      options:
        - Low Priority
        - Medium Priority
        - High Priority
    validations:
      required: true
  - type: textarea
    id: accept-criteria
    attributes:
      label: Acceptance Criteria
      description: Add an acceptance criteria
      placeholder: “Add an acceptance criteria”      
    validations:
      required: true
  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: Make sure to note down all the dependencies needed by referring one of the issue already posted using `#issue number` *(ex. `#1`)*
      placeholder: “Note down all the dependencies needed”
    validations:
      required: true
  - type: textarea
    id: notes-comments
    attributes:
      label: Notes or Comments
      description: If you have any notes or comments, type them out here
      placeholder: “Add notes or comments"