name: Bug Report
description: File a bug report
title: "[BUG] "
labels: ["bug", "bug: unconfirmed"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Fill up the required fields below.
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem.
      placeholder: Bug description here. If applicable, add screenshots to help explain your problem.
    validations:
      required: true
  - type: textarea
    id: what-branch
    attributes:
      label: What branch(es) did the bug occur?
      description: Provide branch name where the bug occur.
      placeholder: For example, `main` or `dev`
      value: "`branch name here`"
    validations:
      required: true
  - type: textarea
    id: steps-reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide steps to reproduce the bug
      placeholder: Provide steps to reproduce the bug
      value: "1. Go to '...'\n2. Go to '...'"
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: A clear and concise description of what you expected to happen.
      value: "- "
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: A clear and concise description of what actually happened.
      value: "- "
    validations:
      required: true
  - type: textarea
    id: environment-desktop
    attributes:
      label: Desktop Environment
      description: A clear and concise information of your device. (Leave blank if not on desktop)
      placeholder: A clear and concise information of your device.
      value: "- **OS** [e.g., Windows 10/11, Ubuntu]: \n
      - **Browser** [e.g., Chrome, Firefox, Safari]: \n
      - **Browser Version** [e.g., 23]: "
  - type: textarea
    id: environment-mobile
    attributes:
      label: Mobile Environment
      description: A clear and concise information of your device. (Leave blank if not on mobile)
      placeholder: A clear and concise information of your device.
      value: "- **Device** [e.g., iPhone 12]: \n
      - **OS** [e.g., iOS, EMUI]: \n
      - **Browser** [e.g., Stock browser, Safari]: \n
      - **Browser Version** [e.g., 23]: "
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: addtl-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: Add any other context about the problem here.